version: "3.1"
services:
  composer:
    image: composer:2.0.9
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - ${PHP_CODE_PATH}:/app
    restart: "no"
  phpunit:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
        - XDEBUG_VERSION=${XDEBUG_VERSION}
    working_dir: /app
    restart: "no"
    entrypoint: vendor/bin/phpunit
    volumes:
      - ${PHP_CODE_PATH}:/app
  php:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: "no"
    volumes:
      - ${PHP_CODE_PATH}:/app
    working_dir: /app
volumes:
  data:
    driver: local
