version: "3.1"
services:
  composer:
    image: composer:2.0.9
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - ${PHP_CODE_PATH}:/app
    restart: "no"
  phpunit:
    build:
      context: .
    working_dir: /app
    restart: "no"
    entrypoint: vendor/bin/phpunit
    volumes:
      - ${PHP_CODE_PATH}:/app
  php:
    build:
      context: .
    restart: "no"
    volumes:
      - ${PHP_CODE_PATH}:/app
    working_dir: /app
volumes:
  data:
    driver: local
